# Project 2: Visualization of global precipitation and global temperature

```{r}
# if(!require("devtools")) install.packages("devtools")
# devtools::install_github("bwlewis/rthreejs

# require(devtools)
# install_github("Displayr/flipChartBasics", dependencies = NA)
```

```{r}
df_surface_temp <- readxl::read_excel('surfaces_temp.xlsx')
df_precipitation <- readxl::read_excel('precipitation.xlsx')
df_precipitation
```

```{r}
?globejs
```

```{r}
library(stringr)

df_precipitation_filtered <- df_precipitation[str_detect(df_precipitation$code, '^[A-Za-z]+$'), ]
df_precipitation_filtered <- df_precipitation_filtered[, c('code', '1901-07')]
df_precipitation_filtered <- na.omit(df_precipitation_filtered)
names(df_precipitation_filtered)[names(df_precipitation_filtered) == '1901-07'] <- 'value'
```

```{r}
dim(df_precipitation_filtered)
```

```{r}
library(globe4r)
world <- create_globe(height = "100vh") %>%
  globe_choropleth(
    coords(
      country = code,
      altitude = value,
      cap_color = value
    ), 
    data = df_precipitation_filtered
  ) %>% 
  scale_choropleth_cap_color() %>%  
  scale_choropleth_altitude(0.06, 0.1) %>%
  show_atmosphere(show = TRUE) %>%
  show_graticules(show = TRUE)

world
```